# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout doc repository
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Run a one-line script
        run: echo ${{ join(github.event.commits.*.id, ' ' ) }}
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      
      - name: Checkout pusher
        uses: actions/checkout@v2
        with:
          repository: vmishenev/kotlin-samples-pusher
          path: pusher
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./pusher/gradlew

      - name: Run a docker with compiler-server
        working-directory: ./pusher
        run: ./gradlew dockerRun
        
      - name: Build with Gradle
        working-directory: ./pusher
        run: |
             ./gradlew build -x test
             ./gradlew installDist

      - name: Run pusher
        working-directory: ./pusher
        run: ./build/install/kotlin-samples-pusher/bin/kotlin-samples-pusher -r https://github.com/${{github.repository}} -f kotlin -pr https://github.com/vmishenev/kotlin-compiler-server -username ${{ secrets.TOKEN }} -path src/test/resources/test-compile-data/kotlin-web-site -commits ,${{ github.event.after }}
