name: Verify samples CRON

on:
  schedule:
   - cron: '30 * * * *' # 5:30 UTC Mon, Thu
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - repo: 'https://github.com/JetBrains/kotlin-web-site'
          filter: '#tag="code" & kotlin-runnable="true"'
          path: 'src/test/resources/test-compile-data/kotlin-web-site'
        - repo: 'https://github.com/Kotlin/kotlin-by-example'
          filter: '#tag="code" & class="language-run-kotlin"'
          path: 'src/test/resources/test-compile-data//kotlin-by-example'
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Run a verifier
        uses: vmishenev/kotlin-samples-pusher@v1
        with:
          io-event: '' #reset default behavior
          repository: '${{ matrix.repo }}'
          verify-branch: 'master'
          push-repository: 'https://github.com/vmishenev/kotlin-compiler-server'
          tag-filter: '${{ matrix.filter }}'
          push-path: '${{ matrix.path }}'
          username: '${{ secrets.TOKEN }}' #token with an access to create PR in push-repository and issue in this repository
